-- F2.2 — dez permissões de oportunidades/pipeline e matriz fechada por papel.

insert into public.permissions (key) values
  ('opportunity.view_own'),
  ('opportunity.view_all'),
  ('opportunity.create'),
  ('opportunity.edit_own'),
  ('opportunity.edit_all'),
  ('opportunity.move_own'),
  ('opportunity.move_all'),
  ('opportunity.close'),
  ('opportunity.reopen'),
  ('pipeline.manage');

insert into public.role_permissions (role, permission) values
  ('owner', 'opportunity.view_own'),
  ('owner', 'opportunity.view_all'),
  ('owner', 'opportunity.create'),
  ('owner', 'opportunity.edit_own'),
  ('owner', 'opportunity.edit_all'),
  ('owner', 'opportunity.move_own'),
  ('owner', 'opportunity.move_all'),
  ('owner', 'opportunity.close'),
  ('owner', 'opportunity.reopen'),
  ('owner', 'pipeline.manage'),
  ('admin', 'opportunity.view_own'),
  ('admin', 'opportunity.view_all'),
  ('admin', 'opportunity.create'),
  ('admin', 'opportunity.edit_own'),
  ('admin', 'opportunity.edit_all'),
  ('admin', 'opportunity.move_own'),
  ('admin', 'opportunity.move_all'),
  ('admin', 'opportunity.close'),
  ('admin', 'opportunity.reopen'),
  ('admin', 'pipeline.manage'),
  ('manager', 'opportunity.view_own'),
  ('manager', 'opportunity.view_all'),
  ('manager', 'opportunity.create'),
  ('manager', 'opportunity.edit_own'),
  ('manager', 'opportunity.edit_all'),
  ('manager', 'opportunity.move_own'),
  ('manager', 'opportunity.move_all'),
  ('manager', 'opportunity.close'),
  ('sdr', 'opportunity.view_own'),
  ('sdr', 'opportunity.create'),
  ('sdr', 'opportunity.edit_own'),
  ('sdr', 'opportunity.move_own'),
  ('sdr', 'opportunity.close'),
  ('receptionist', 'opportunity.view_own'),
  ('receptionist', 'opportunity.view_all'),
  ('professional', 'opportunity.view_own'),
  ('viewer', 'opportunity.view_all');
